[build]
  command = "pip install -r requirements.txt && cp -r templates/* public/ && cp -r static/* public/static/"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/predict"
  to = "/.netlify/functions/predict"
  status = 200
  
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
